language: python
dist: xenial
python:
  - "3.7"
services:
  - docker
before_script:
  - .travis/build_and_test.sh
script:
  - docker-compose exec django /home/django/.local/bin/coverage run --source=terra manage.py test terra
after_success:
  coveralls
