version: '3'
services:
  django:
    build: .
    ports:
     - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: this-is-a-fake-password
      MYSQL_DATABASE: terra
      MYSQL_USER: terrauser
      MYSQL_PASSWORD: terra-fake-password
    ports:
      - "3306:3306"
