version: '3'
services:
  django:
    image: uclalibrary/terra:latest
    volumes:
      - .:/home/django/terra
    env_file:
      - .docker-compose_django.env
      - .docker-compose_db.env
    ports:
     - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .docker-compose_db.env
    ports:
      - "3306:3306"
