apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "terra.fullname" . }}-externalsecret
  namespace: terra{{ .Values.django.env.run_env }}
  {{- with .Values.django.externalSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: systems-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "terra.fullname" . }}-secrets
  data:
    - secretKey: "DJANGO_SECRET_KEY"
      remoteRef:
        key: {{ .Values.django.externalSecrets.env.django_secret_key }}
    - secretKey: "DJANGO_DB_PASSWORD"
      remoteRef:
        key: {{ .Values.django.externalSecrets.env.db_password }}
