{{ if not .Values.django.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terra.fullname" . }}-secrets
  namespace: terra{{ .Values.django.env.run_env }}
  labels:
{{ include "terra.fullname" . | indent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  DJANGO_DB_PASSWD: {{ .Values.django.env.db_passwd | b64enc | quote }}
{{ end }}