# Default values for TERRA app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: uclalibrary/terra
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

django:
  env:
    run_env: "prod"
    debug: "false"
    allowed_hosts: []
    #  - localhost
    #  - 127.0.0.1
    #  - [::1]
    db_name: ""
    db_user: ""
    db_host: ""
    # Include if externalSecrets enabled: "false"
    #db_passwd: ""
    test_db_name: ""
    email_host: ""
    target_port: ""

  externalSecrets:
    enabled: "false"
    env: {}
    # Include below if enabled: "true"
    #  db_password: ""
    #  django_secret_key: ""  

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

