version: '3'
services:
  django:
    build: ..
    image: uclalibrary/terra:test
    volumes:
      - ..:/home/django/terra
    env_file:
      - ../.docker-compose_django.env
    ports:
     - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../.docker-compose_db.env
    ports:
      - "3306:3306"
