name: Build and test TERRA
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and run containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with: 
          compose-file: "./docker-compose.yml"
          # --build to use current code, not pull image... may not work
          up-flags: "--build"
      - name: Wait for services
        # Wait 10 seconds to allow database container to spin up
        run: sleep 10
      - name: Run tests
        # Use exec -T to avoid creating unusable pseudo-TTY
        run: docker compose exec -T django python manage.py test
