name: Build and test TERRA
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and run containers
        uses: isbang/compose-action@v1.4.1
        with: 
          compose-file: "./docker-compose.yml"
      - name: Run tests
        run: docker-compose exec django python manage.py test
