name: Build and test TERRA
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and run containers
        uses: cloudposse/github-action-docker-compose-test-run@main
        with: 
          file: "./docker-compose.yml"
          entrypoint: "./docker/entrypoint.sh"
          service: django
          command: django python manage.py test
